export const OFFICIAL_AI_MODEL_PRICING = [
  {
    provider: "openai",
    model: "gpt-5.5",
    inputUsdPerMillion: "5",
    cachedInputUsdPerMillion: "0.5",
    outputUsdPerMillion: "30",
    sourceUrl: "https://developers.openai.com/api/docs/pricing",
    sourceNote: "OpenAI standard text token pricing, short context",
  },
  {
    provider: "openai",
    model: "gpt-5.4",
    inputUsdPerMillion: "2.5",
    cachedInputUsdPerMillion: "0.25",
    outputUsdPerMillion: "15",
    sourceUrl: "https://developers.openai.com/api/docs/pricing",
    sourceNote: "OpenAI standard text token pricing, short context",
  },
  {
    provider: "openai",
    model: "gpt-5.4-mini",
    inputUsdPerMillion: "0.75",
    cachedInputUsdPerMillion: "0.075",
    outputUsdPerMillion: "4.5",
    sourceUrl: "https://developers.openai.com/api/docs/pricing",
    sourceNote: "OpenAI standard text token pricing, short context",
  },
  {
    provider: "openai",
    model: "gpt-5.4-nano",
    inputUsdPerMillion: "0.2",
    cachedInputUsdPerMillion: "0.02",
    outputUsdPerMillion: "1.25",
    sourceUrl: "https://developers.openai.com/api/docs/pricing",
    sourceNote: "OpenAI standard text token pricing, short context",
  },
  {
    provider: "openai",
    model: "gpt-4o-mini",
    inputUsdPerMillion: "0.15",
    cachedInputUsdPerMillion: "0.075",
    outputUsdPerMillion: "0.6",
    sourceUrl: "https://developers.openai.com/api/docs/pricing",
    sourceNote: "OpenAI standard text token pricing",
  },
  {
    provider: "anthropic",
    model: "claude-opus-4-7",
    inputUsdPerMillion: "5",
    cachedInputUsdPerMillion: "0.5",
    outputUsdPerMillion: "25",
    sourceUrl: "https://platform.claude.com/docs/en/about-claude/pricing",
    sourceNote: "Anthropic Claude API model pricing",
  },
  {
    provider: "anthropic",
    model: "claude-opus-4-6",
    inputUsdPerMillion: "5",
    cachedInputUsdPerMillion: "0.5",
    outputUsdPerMillion: "25",
    sourceUrl: "https://platform.claude.com/docs/en/about-claude/pricing",
    sourceNote: "Anthropic Claude API model pricing",
  },
  {
    provider: "anthropic",
    model: "claude-opus-4-5",
    inputUsdPerMillion: "5",
    cachedInputUsdPerMillion: "0.5",
    outputUsdPerMillion: "25",
    sourceUrl: "https://platform.claude.com/docs/en/about-claude/pricing",
    sourceNote: "Anthropic Claude API model pricing",
  },
  {
    provider: "anthropic",
    model: "claude-sonnet-4-6",
    inputUsdPerMillion: "3",
    cachedInputUsdPerMillion: "0.3",
    outputUsdPerMillion: "15",
    sourceUrl: "https://platform.claude.com/docs/en/about-claude/pricing",
    sourceNote: "Anthropic Claude API model pricing",
  },
  {
    provider: "anthropic",
    model: "claude-sonnet-4-5",
    inputUsdPerMillion: "3",
    cachedInputUsdPerMillion: "0.3",
    outputUsdPerMillion: "15",
    sourceUrl: "https://platform.claude.com/docs/en/about-claude/pricing",
    sourceNote: "Anthropic Claude API model pricing",
  },
  {
    provider: "anthropic",
    model: "claude-haiku-4-5",
    inputUsdPerMillion: "1",
    cachedInputUsdPerMillion: "0.1",
    outputUsdPerMillion: "5",
    sourceUrl: "https://platform.claude.com/docs/en/about-claude/pricing",
    sourceNote: "Anthropic Claude API model pricing",
  },
  {
    provider: "anthropic",
    model: "claude-haiku-3-5",
    inputUsdPerMillion: "0.8",
    cachedInputUsdPerMillion: "0.08",
    outputUsdPerMillion: "4",
    sourceUrl: "https://platform.claude.com/docs/en/about-claude/pricing",
    sourceNote: "Anthropic Claude API model pricing",
  },
];

